version: "2"

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  elasticsearch:
    image: elasticsearch
    expose:
      - "9200"

  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  web: &api_base
    build: .
    command: mix phoenix.server
    depends_on:
      - postgres
      - elasticsearch
    environment: &api_environment
      MIX_ENV: dev
      PORT: 4000
      DATABASE_POSTGRESQL_HOST: postgres
      DATABASE_POSTGRESQL_USERNAME: postgres
      VIRTUAL_HOST: lvh.me,api.lvh.me
    links:
      - postgres
      - elasticsearch
    ports:
      - 4001:4000
    volumes:
      - .:/code-corps-api

  test:
    <<: *api_base
    command: mix test
    environment:
      <<: *api_environment
      MIX_ENV: test
      PORT: 4001
    ports:
      - 4002:4001

  apiary:
    image: apiaryio/client
    command: preview --server --host=0.0.0.0 --port=8080 --path=/code-corps-api/blueprint/api.apib
    ports:
      - 8081:8080
    volumes:
      - .:/code-corps-api

volumes:
  postgres-data:
